module.exports = [
	{
		id: 'job-1000',
		title: 'React Developer',
		location: 'London',
		salary: 75000,
		type: 'Permanent',
		company: 'Acme Company',
		post_date: '14 days ago',
		description: 'React Developer Circa £75,000 City of London The React Developer will work on a re-platforming of existing products to take advantage … The React Developer will benefit from working in a purely greenfield project',
		logo: 'https://logo.clearbit.com/company.com',
	},
	{
		id: 'job-1001',
		title: 'Web Developer',
		location: 'London',
		salary: 80000,
		type: 'Permanent',
		company: 'Acme Company',
		post_date: '10 days ago',
		description: 'Senior .NET Full Stack Developer - Reigate - Insurance - Azure Cloud / .NET Core / Angular … Net Full Stack Developer to be based at their offices in Reigate. Role & Responsibilities: … casual dress code • Free coffee machine and fruit Senior .NET Full Stack',
		logo: 'https://logo.clearbit.com/company.com',
	},
	{
		id: 'job-1002',
		title: 'Web Developer',
		location: 'Manchester',
		salary: 90000,
		type: 'Permanent',
		company: 'Acme Company',
		post_date: '1 days ago',
		description: 'High-quality Lead Node.js Developer required for tech-driven Green Energy organisation based in Central London The sucessful Node.js Developer will be working on a greenfield project, heading up a small, Agile team of NodeJS Developers.',
		logo: 'https://logo.clearbit.com/company.com',
	},
	{
		id: 'job-1003',
		title: 'React Developer',
		location: 'London',
		salary: 75000,
		type: 'Permanent',
		company: 'Acme Company',
		post_date: '6 days ago',
		description: 'React Developer Circa £75,000 City of London - Marylebone (NW1) ? ShortList Recruitment … The React Developer will work on a re-platforming of existing products to take advantage … The React Developer will benefit from working in a purely greenfield project',
		logo: 'https://logo.clearbit.com/company.com',
	},
	{
		id: 'job-1004',
		title: 'Python Developer',
		location: 'Manchester',
		salary: 80000,
		type: 'Permanent',
		company: 'Acme Company',
		post_date: '2 days ago',
		description: 'Senior .NET Full Stack Developer - Reigate - Insurance - Azure Cloud / .NET Core / Angular … Net Full Stack Developer to be based at their offices in Reigate. Role & Responsibilities: … casual dress code • Free coffee machine and fruit Senior .NET Full Stack',
		logo: 'https://logo.clearbit.com/company.com',
	},
	{
		id: 'job-1005',
		title: 'Python Developer',
		location: 'Liverpool',
		salary: 90000,
		type: 'Permanent',
		company: 'Acme Company',
		post_date: '3 days ago',
		description: 'High-quality Lead Node.js Developer required for tech-driven Green Energy organisation based in Central London The sucessful Node.js Developer will be working on a greenfield project',
		logo: 'https://logo.clearbit.com/company.com',
	},
	{
		id: 'job-1006',
		title: 'Go Developer',
		location: 'Manchester',
		salary: 80000,
		type: 'Permanent',
		company: 'Acme Company',
		post_date: '20 days ago',
		description: 'Senior .NET Full Stack Developer - Reigate - Insurance - Azure Cloud / .NET Core / Angular … Net Full Stack Developer to be based at their offices in Reigate. Role & Responsibilities: … casual dress code • Free coffee machine and fruit Senior .NET Full Stack',
		logo: 'https://logo.clearbit.com/company.com',
	},
	{
		id: 'job-1007',
		title: 'Scala Developer',
		location: 'Liverpool',
		salary: 90000,
		type: 'Permanent',
		company: 'Acme Company',
		post_date: '16 days ago',
		description: 'High-quality Lead Node.js Developer required for tech-driven Green Energy organisation based in Central London The sucessful Node.js Developer will be working on a greenfield project, heading up a small, Agile team of NodeJS Developers, ranging from Junior level to Senior, while remaining ~50% hands-on in terms of coding. ',
		logo: 'https://logo.clearbit.com/company.com',
	},
	{
		id: 'job-1008',
		title: 'React Developer',
		location: 'London',
		salary: 80000,
		type: 'Permanent',
		company: 'Acme Company',
		post_date: '30 days ago',
		description: 'Senior .NET Full Stack Developer - Reigate - Insurance - Azure Cloud / .NET Core / Angular … Net Full Stack Developer to be based at their offices in Reigate. Role & Responsibilities: … casual dress code • Free coffee machine and fruit Senior .NET Full Stack',
		logo: 'https://logo.clearbit.com/company.com',
	},
	{
		id: 'job-1009',
		title: 'NodeJS Developer',
		location: 'Liverpool',
		salary: 60000,
		type: 'Permanent',
		company: 'Acme Company',
		post_date: '21 days ago',
		description: 'High-quality Junior Developer required for tech-driven Green Energy organisation based in Central London The sucessful Node.js Developer will be working on a greenfield project, heading up a small, Agile team of NodeJS Developers, ranging from Junior level to Senior, while remaining ~50% hands-on in terms of coding.',
		logo: 'https://logo.clearbit.com/company.com',
	},
	{
		id: 'job-1010',
		title: 'Web Developer',
		location: 'Bristol',
		salary: 50000,
		type: 'Permanent',
		company: 'Acme Company',
		post_date: '19 days ago',
		description: 'High-quality Lead Node.js Developer required for tech-driven Green Energy organisation based in Central London The sucessful Node.js Developer will be working on a greenfield project, heading up a small, Agile team of NodeJS Developers, ranging from Junior level to Senior, while remaining ~50% hands-on in terms of coding. ',
		logo: 'https://logo.clearbit.com/company.com',
	},
];
